# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or create!d alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create!([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create!(name: 'Luke', movie: movies.first)

Ingredient.create!(name: 'bitters')
Ingredient.create!(name: 'bourbon')
Ingredient.create!(name: 'brandy')
Ingredient.create!(name: 'brown sugar')
Ingredient.create!(name: 'compari')
Ingredient.create!(name: 'club soda')
Ingredient.create!(name: 'cola')
Ingredient.create!(name: 'cranberry juice')
Ingredient.create!(name: 'cream')
Ingredient.create!(name: 'dark rum')
Ingredient.create!(name: 'dry vermouth')
Ingredient.create!(name: 'galliano')
Ingredient.create!(name: 'gin')
Ingredient.create!(name: 'ginger beer')
Ingredient.create!(name: 'grenadine')
Ingredient.create!(name: 'hot coffee')
Ingredient.create!(name: 'kahlua')
Ingredient.create!(name: 'lemon juice')
Ingredient.create!(name: 'light rum')
Ingredient.create!(name: 'lime juice')
Ingredient.create!(name: 'mint')
Ingredient.create!(name: 'olive juice')
Ingredient.create!(name: 'orange juice')
Ingredient.create!(name: 'orange liqueur')
Ingredient.create!(name: 'pisco')
Ingredient.create!(name: 'rye')
Ingredient.create!(name: 'simple syrup')
Ingredient.create!(name: 'sugar')
Ingredient.create!(name: 'sweet vermouth')
Ingredient.create!(name: 'tequila')
Ingredient.create!(name: 'triple sec')
Ingredient.create!(name: 'vodka')
Ingredient.create!(name: 'whiskey')

Drink.create!(name: 'Old Fashioned')
Drink.create!(name: 'Manhattan')
Drink.create!(name: 'Daiquiri')
Drink.create!(name: 'Sidecar')
Drink.create!(name: 'Irish Coffee')
Drink.create!(name: 'Negroni')
Drink.create!(name: 'Boulevardier')
Drink.create!(name: 'Mint Julep')
Drink.create!(name: 'Whiskey Sour')
Drink.create!(name: 'Pisco Sour')
Drink.create!(name: 'Cosmopolitan')
Drink.create!(name: 'White Russian')
Drink.create!(name: 'Dirty Martini')
Drink.create!(name: 'Americano')
Drink.create!(name: 'Cuba Libre')
Drink.create!(name: 'Gin Gimlet')
Drink.create!(name: 'Moscow Mule')
Drink.create!(name: 'Revolver')
Drink.create!(name: 'Tequila Sunrise')
Drink.create!(name: 'Harvey Wallbanger')

MixedDrink.create!(drink_id: 1, ingredient_id: 1)
MixedDrink.create!(drink_id: 1, ingredient_id: 2)
MixedDrink.create!(drink_id: 1, ingredient_id: 28)

MixedDrink.create!(drink_id: 2, ingredient_id: 1)
MixedDrink.create!(drink_id: 2, ingredient_id: 26)
MixedDrink.create!(drink_id: 2, ingredient_id: 29)

MixedDrink.create!(drink_id: 3, ingredient_id: 19)
MixedDrink.create!(drink_id: 3, ingredient_id: 20)
MixedDrink.create!(drink_id: 3, ingredient_id: 28)

MixedDrink.create!(drink_id: 4, ingredient_id: 3)
MixedDrink.create!(drink_id: 4, ingredient_id: 18)
MixedDrink.create!(drink_id: 4, ingredient_id: 24)

MixedDrink.create!(drink_id: 5, ingredient_id: 4)
MixedDrink.create!(drink_id: 5, ingredient_id: 16)
MixedDrink.create!(drink_id: 5, ingredient_id: 33)

MixedDrink.create!(drink_id: 6, ingredient_id: 5)
MixedDrink.create!(drink_id: 6, ingredient_id: 13)
MixedDrink.create!(drink_id: 6, ingredient_id: 29)

MixedDrink.create!(drink_id: 7, ingredient_id: 33)
MixedDrink.create!(drink_id: 7, ingredient_id: 29)
MixedDrink.create!(drink_id: 7, ingredient_id: 5)

MixedDrink.create!(drink_id: 8, ingredient_id: 2)
MixedDrink.create!(drink_id: 8, ingredient_id: 21)
MixedDrink.create!(drink_id: 8, ingredient_id: 28)

MixedDrink.create!(drink_id: 9, ingredient_id: 18)
MixedDrink.create!(drink_id: 9, ingredient_id: 28)
MixedDrink.create!(drink_id: 9, ingredient_id: 33)

MixedDrink.create!(drink_id: 10, ingredient_id: 18)
MixedDrink.create!(drink_id: 10, ingredient_id: 25)
MixedDrink.create!(drink_id: 10, ingredient_id: 27)

MixedDrink.create!(drink_id: 11, ingredient_id: 8)
MixedDrink.create!(drink_id: 11, ingredient_id: 31)
MixedDrink.create!(drink_id: 11, ingredient_id: 32)

MixedDrink.create!(drink_id: 12, ingredient_id: 32)
MixedDrink.create!(drink_id: 12, ingredient_id: 17)
MixedDrink.create!(drink_id: 12, ingredient_id: 9)

MixedDrink.create!(drink_id: 13, ingredient_id: 11)
MixedDrink.create!(drink_id: 13, ingredient_id: 13)
MixedDrink.create!(drink_id: 13, ingredient_id: 22)

MixedDrink.create!(drink_id: 14, ingredient_id: 5)
MixedDrink.create!(drink_id: 14, ingredient_id: 6)
MixedDrink.create!(drink_id: 14, ingredient_id: 29)

MixedDrink.create!(drink_id: 15, ingredient_id: 7)
MixedDrink.create!(drink_id: 15, ingredient_id: 10)
MixedDrink.create!(drink_id: 15, ingredient_id: 20)

MixedDrink.create!(drink_id: 16, ingredient_id: 13)
MixedDrink.create!(drink_id: 16, ingredient_id: 20)
MixedDrink.create!(drink_id: 16, ingredient_id: 27)

MixedDrink.create!(drink_id: 17, ingredient_id: 32)
MixedDrink.create!(drink_id: 17, ingredient_id: 20)
MixedDrink.create!(drink_id: 17, ingredient_id: 14)

MixedDrink.create!(drink_id: 18, ingredient_id: 1)
MixedDrink.create!(drink_id: 18, ingredient_id: 17)
MixedDrink.create!(drink_id: 18, ingredient_id: 33)

MixedDrink.create!(drink_id: 19, ingredient_id: 15)
MixedDrink.create!(drink_id: 19, ingredient_id: 23)
MixedDrink.create!(drink_id: 19, ingredient_id: 30)

MixedDrink.create!(drink_id: 20, ingredient_id: 32)
MixedDrink.create!(drink_id: 20, ingredient_id: 23)
MixedDrink.create!(drink_id: 20, ingredient_id: 12)

User.create!(email: "lori@example.com", password: "password")
User.create!(email: "samantha@example.com", password: "carolina")
User.create!(email: "sam@example.com", password: "musician")

Game.create!(session: 1, user_id: 1, drink_id: 1)
Game.create!(session: 1, user_id: 1, drink_id: 2)
Game.create!(session: 1, user_id: 1, drink_id: 3)
Game.create!(session: 1, user_id: 1, drink_id: 4)
Game.create!(session: 1, user_id: 1, drink_id: 5)

Game.create!(session: 2, user_id: 2, drink_id: 5)
Game.create!(session: 2, user_id: 2, drink_id: 6)
Game.create!(session: 2, user_id: 2, drink_id: 10)
Game.create!(session: 2, user_id: 2, drink_id: 12)
Game.create!(session: 2, user_id: 2, drink_id: 1)

Game.create!(session: 1, user_id: 3, drink_id: 1)
Game.create!(session: 1, user_id: 3, drink_id: 20)
Game.create!(session: 1, user_id: 3, drink_id: 13)
Game.create!(session: 1, user_id: 3, drink_id: 18)
Game.create!(session: 1, user_id: 3, drink_id: 5)

Game.create!(session: 2, user_id: 1, drink_id: 7)
Game.create!(session: 2, user_id: 1, drink_id: 20)
Game.create!(session: 2, user_id: 1, drink_id: 13)
Game.create!(session: 2, user_id: 1, drink_id: 18)
Game.create!(session: 2, user_id: 1, drink_id: 8)
