# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Ingredient.new(name: 'bitters')
Ingredient.new(name: 'bourbon')
Ingredient.new(name: 'brandy')
Ingredient.new(name: 'brown sugar')
Ingredient.new(name: 'compari')
Ingredient.new(name: 'club soda')
Ingredient.new(name: 'cola')
Ingredient.new(name: 'cranberry juice')
Ingredient.new(name: 'cream')
Ingredient.new(name: 'dark rum')
Ingredient.new(name: 'dry vermouth')
Ingredient.new(name: 'galliano')
Ingredient.new(name: 'gin')
Ingredient.new(name: 'ginger beer')
Ingredient.new(name: 'grenadine')
Ingredient.new(name: 'hot coffee')
Ingredient.new(name: 'kahlua')
Ingredient.new(name: 'lemon juice')
Ingredient.new(name: 'light rum')
Ingredient.new(name: 'lime juice')
Ingredient.new(name: 'mint')
Ingredient.new(name: 'olive juice')
Ingredient.new(name: 'orange juice')
Ingredient.new(name: 'orange liqueur')
Ingredient.new(name: 'pisco')
Ingredient.new(name: 'rye')
Ingredient.new(name: 'simple syrup')
Ingredient.new(name: 'sugar')
Ingredient.new(name: 'sweet vermouth')
Ingredient.new(name: 'tequila')
Ingredient.new(name: 'triple sec')
Ingredient.new(name: 'vodka')
Ingredient.new(name: 'whiskey')

Drink.new(name: 'Old Fashioned')
Drink.new(name: 'Manhattan')
Drink.new(name: 'Daiquiri')
Drink.new(name: 'Sidecar')
Drink.new(name: 'Irish Coffee')
Drink.new(name: 'Negroni')
Drink.new(name: 'Boulevardier')
Drink.new(name: 'Mint Julep')
Drink.new(name: 'Whiskey Sour')
Drink.new(name: 'Pisco Sour')
Drink.new(name: 'Cosmopolitan')
Drink.new(name: 'White Russian')
Drink.new(name: 'Dirty Martini')
Drink.new(name: 'Americano')
Drink.new(name: 'Cuba Libre')
Drink.new(name: 'Gin Gimlet')
Drink.new(name: 'Moscow Mule')
Drink.new(name: 'Revolver')
Drink.new(name: 'Tequila Sunrise')
Drink.new(name: 'Harvey Wallbanger')
